#!/bin/bash

function runJava(){
	local project_folder=$1
	local test_suite_folder=$2
	local state=$3
	local express_server_port=$4
	mvn exec:java -Dexec.mainClass="code.Main" -Dexec.args="$project_folder $test_suite_folder $state $express_server_port" \
		-Dexec.cleanupDaemonThreads=false -f $project_folder/pom.xml
}

# -----------------------------------------------------------------------------------------------------------

project_name=$1
session_file_name=$2
db_port=$3
app_port=$4
chromedriver_port=$5
test_suite_folder=$6
project_folder=$7
production=$8
express_server_port=$9
test_suite_counter=${10}

if [[ $project_name != "default" && $project_name != "pagekit" && $project_name != "dimeshift" \
		&& $project_name != "splittypie" && $project_name != "phoenix" \
		&& $project_name != "retroboard" && $project_name != "petclinic" ]]; then
	echo Please choose a correct project name
	usage
	exit 1
fi

if [ -z "$session_file_name" ]; then
	echo Please set session file name. Cannot be empty!
	usage
	exit 1
fi

if [[ $project_name == "dimeshift" ]]; then
	if [ -z "$db_port" ]; then
		echo Please set the db port for  $project_name
		usage
		exit 1	
	fi
fi

if [[ $project_name == "pagekit" ]]; then
	if [ -z "$db_port" ]; then
		echo Please set the db port for  $project_name
		usage
		exit 1	
	fi
fi

if [[ $project_name == "phoenix" ]]; then
	if [ -z "$db_port" ]; then
		echo Please set the db port for  $project_name
		usage
		exit 1	
	fi
fi

if [[ $project_name == "petclinic" ]]; then
	if [ -z "$db_port" ]; then
		echo Please set the db port for  $project_name
		usage
		exit 1	
	fi
fi


if [ -z "$app_port" ]; then
	echo Please set the app port. Cannot be empty!
	usage
	exit 1
fi

if [ -z "$chromedriver_port" ]; then
	echo Please set chromedriver port. Cannot be empty!
	usage
	exit 1
fi

if [ -z "$express_server_port" ]; then
	echo Please set express server port. Cannot be empty!
	usage
	exit 1
fi

if [ -z "$test_suite_folder" ]; then
	echo Please set the directory of the tests automatically generated by evosuite. Cannot be empty!
	usage
	exit 1
fi

if [ -z "$project_folder" ]; then
	echo Please set the project folder. Cannot be empty!
	usage
	exit 1
fi

if [ -z "$test_suite_counter" ]; then
	echo Please set the test suite counter. Cannot be empty!
	usage
	exit 1
fi

echo
echo Project name: $project_name
echo Session file name: $session_file_name
echo Database port for remote connection: $db_port
echo Application port for remote connection: $app_port
echo Chromedriver port: $chromedriver_port
echo Project folder: $project_folder
echo Express server port: $express_server_port
echo Test suite counter: $test_suite_counter
echo

driver_headless=false
if [[ $production == "true" ]]; then
    driver_headless=true
else
    driver_headless=false
fi

properties_file_path=$project_folder/src/main/resources/app.properties
session_file_name_with_counter=$session_file_name-$test_suite_counter
cat >$properties_file_path <<EOL
chromedriverPort=${chromedriver_port}
dbPort=${db_port}
appPort=${app_port}
driverHeadless=${driver_headless}
EOL

state=modify_test_suite
runJava $project_folder $test_suite_folder $state $express_server_port \
	> $test_suite_folder/modify-test-suite-$session_file_name-$test_suite_counter.txt

compilation_exceptions=0
mvn clean compile -f $project_folder/pom.xml \
	> $test_suite_folder/compile-test-suite-$session_file_name-$test_suite_counter.txt
compilation_exceptions=$(grep -i "BUILD FAILURE" $test_suite_folder/compile-test-suite-$session_file_name-$test_suite_counter.txt | wc -l | awk '{print $1}')
if [ $compilation_exceptions -gt 0 ]; then
	echo "Build failure. Check modify_test_suite \
	    ($test_suite_folder/compile-test-suite-$session_file_name-$test_suite_counter.txt) state to see what is wrong!"
	exit 1
fi

state=code_coverage
runJava $project_folder $test_suite_folder $state $express_server_port \
	> $test_suite_folder/code-coverage-$session_file_name-$test_suite_counter.txt

test_suite_bug=0
test_suite_bug=$(grep -i "Test execution failed" $test_suite_folder/code-coverage-$session_file_name-$test_suite_counter.txt | wc -l | awk '{print $1}')
if [ $test_suite_bug -gt 0 ]; then
	echo Test suite bug found in $test_suite_folder.
	echo Repeat execution of test suite $test_suite_folder or change it with another one.
else
	complete_file_name=$test_suite_folder/complete-$session_file_name-$test_suite_counter.txt
	echo No test suite bug in $test_suite_folder > $complete_file_name
fi
